version: '3'
services:
  app:
    build:
      context: ./
    container_name: next-docker
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    # command: sh -c "yarn install && yarn build && yarn start"
    command: tail -f /dev/null